/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com) All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

package policyv1alpha2

import policyenginev1 "github.com/wso2/api-platform/sdk/core/policyengine"

// Body represents HTTP request or response body data
type Body struct {
	// Content is the body payload (may be nil)
	Content []byte

	// EndOfStream indicates if this is the final chunk of body data
	// true = complete body received, false = more chunks may follow
	EndOfStream bool

	// Present indicates if body data is available
	// false = body was not sent or not buffered (e.g., streaming)
	// true = body is available (Content may still be nil for empty bodies)
	Present bool
}

// DownstreamContext identifies the downstream client and carries a snapshot of
// the client request.
type DownstreamContext struct {
	Request *DownstreamRequest
}

// DownstreamRequest holds a snapshot of the request as received from the
// downstream client, captured before any policy mutation is applied.
type DownstreamRequest struct {
	Headers   *Headers
	Path      string
	Method    string
	Authority string
	Scheme    string

	// Body is a snapshot of the request body as received from the downstream
	// client, captured before any policy's body-phase mutation is applied —
	// the body-phase counterpart to Headers above. Only populated for a
	// buffered (non-streaming) request body; nil (Body.Present == false) for
	// a streaming request, since no single complete body ever exists to
	// snapshot in that mode. A body-phase policy's own mutation (e.g. a
	// translator rewriting the payload for one specific backend) is never
	// reflected here, so anything that needs to replay the client's true
	// original request — not what an earlier policy already turned it into —
	// can rely on this instead of the live, mutable RequestContext.Body.
	Body *Body
}

// UpstreamRequestContext identifies the route's resolved upstream target during
// the request phase.
type UpstreamRequestContext struct {
	Name     string
	URL      string
	BasePath string
}

// UpstreamResponseContext identifies the route's resolved upstream target during
// the response phase and carries a snapshot of the upstream response.
type UpstreamResponseContext struct {
	Name     string
	URL      string
	BasePath string
	Response *UpstreamResponse
}

// UpstreamResponse holds a snapshot of the response as received from the
// upstream backend, captured before any policy mutation is applied.
type UpstreamResponse struct {
	Headers    *Headers
	StatusCode int
}

// SharedContext contains data shared across request and response phases
type SharedContext struct {
	// ProjectID is the project ID which the API is associated with
	ProjectID string

	// Unique request identifier for correlation
	// Generated by Kernel, immutable
	RequestID string

	// Shared metadata for inter-policy communication
	// Persists from request phase through response phase
	// Policies read/write this map to coordinate behavior
	Metadata map[string]interface{}

	// API metadata fields (populated by policy engine at request time)
	// These provide context about which API and operation is being processed

	// APIId is the unique identifier of the API (e.g., UUID)
	APIId string

	// APIName is the name of the API (e.g., "PetStore")
	APIName string

	// APIVersion is the version of the API (e.g., "v1.0.0")
	APIVersion string

	// APIKind is the type of the API
	APIKind APIKind

	// APIContext is the base context path of the API (e.g., "/petstore")
	// This is the base path without the version
	APIContext string

	// OperationPath is the operation path pattern from the API definition
	// (e.g., "/pets/{id}" for a parameterized path)
	// This differs from RequestHeaderContext.Path which contains the actual request path
	// with resolved parameters (e.g., "/petstore/v1.0.0/pets/123")
	OperationPath string

	// ResolvedOperation is the canonical protocol operation this request resolved
	// to, on an API kind whose operation cannot be read off the route.
	//
	// OperationPath is not a substitute. A multiplexed transport puts every
	// operation on one path — an A2A JSON-RPC endpoint serves all eleven
	// operations at the same URL — so OperationPath is identical for all of them
	// and the operation is only knowable after the request has been inspected.
	//
	// Written by the policy engine once the request's policy chain has been
	// bound, before any policy in that chain runs, and derived from the same
	// chain key that selected the chain. It therefore cannot name one operation
	// while another operation's policies (its authentication, its rate limits)
	// actually ran.
	//
	// Empty for a route whose chain is fixed by the route itself, which is every
	// API kind that shipped before Agent — so a policy must treat "" as "not
	// applicable", never as a failure.
	ResolvedOperation string

	// ResolutionAttributes are the protocol-derived facts about this request that
	// the route's resolver captured in the same pass that identified the
	// operation — an A2A message's contextId and taskId, for instance.
	//
	// They exist so the request payload is parsed once, and they are the only way
	// a body-sourced value can reach a *request-header-phase* policy, since
	// RequestHeaderContext carries no body of its own. Read via Get, Lookup, Len
	// and Iterate; see ResolutionAttributes for what may be in here, how far it
	// can be trusted, and why it is not a plain map.
	//
	// The zero value is the empty set, which is what a route resolved by the route
	// itself carries — so, as with ResolvedOperation above, a policy reads "no
	// attributes" as "not applicable" rather than as a failure to resolve.
	ResolutionAttributes ResolutionAttributes

	// AuthContext stores structured authentication information populated by auth policies.
	// Nil until an auth policy runs. Use Previous for multi-layer auth chains.
	AuthContext *AuthContext

	// AttemptNumber counts which attempt, in a chain of self-originated retries, this
	// request is — 1 for a genuine, first-arrival client request; 2 for the first retry a
	// policy originates itself, and so on. Populated by the policy engine from the
	// AttemptNumberHeader request header (see its own doc), defaulting to 1 when that header
	// is absent, so an ordinary request that never gets retried always reads 1.
	//
	// This exists because each retry a policy originates (e.g. model-failover's self-redial,
	// or oauth2-generator's own upstream retry-on-401-refresh) is a genuinely new, independent
	// stream from the kernel's point of view — there is no shared in-memory state linking it
	// back to the request that triggered it (see AttemptNumberHeader). AttemptNumber is the
	// one piece of that lineage the kernel surfaces as a typed field, for logging/tracing/
	// observability, rather than every consumer re-parsing the raw header itself.
	//
	// A policy originating a retry is responsible for setting AttemptNumberHeader on its own
	// outbound call to CurrentAttemptNumber()+1 (see that helper) — the kernel only reads the
	// header on the way in, it never increments anything on its own.
	AttemptNumber int
}

// AttemptNumberHeader is the well-known request header a self-retrying policy sets on its
// own outbound retry so the kernel can populate SharedContext.AttemptNumber on that retry's
// own (separate, independent) stream. Shared across every such policy in this codebase
// (model-failover's self-redial, oauth2-generator's own upstream retry-on-401-refresh, and
// any future one) so they all carry attempt lineage the same way, rather than each inventing
// its own ad-hoc header. Absent entirely on a genuine first-arrival client request — a policy
// must never rely on a client to have sent this header itself; only ever set by a policy on
// its own self-originated retry.
const AttemptNumberHeader = "x-wso2-attempt-number"

// CurrentAttemptNumber returns the attempt number to report on the NEXT retry a policy is
// about to originate from this request — i.e. shared.AttemptNumber+1, or 2 if shared is nil
// (defensive: AttemptNumber's own zero value would otherwise read as attempt 1, understating
// a retry that's about to become attempt 2). Set this on AttemptNumberHeader on the retry's
// own outbound request.
func CurrentAttemptNumber(shared *SharedContext) int {
	if shared == nil || shared.AttemptNumber < 1 {
		return 2
	}
	return shared.AttemptNumber + 1
}

// ─── Request-phase contexts ──────────────────────────────────────────────────

// RequestHeaderContext is passed to RequestHeaderPolicy.OnRequestHeaders.
// The request body is not yet available at this phase.
type RequestHeaderContext struct {
	*SharedContext

	// Current request headers (read-only for policies)
	Headers   *Headers
	Path      string
	Method    string
	Authority string
	Scheme    string
	Vhost     string

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target for this
	// request.
	Upstream *UpstreamRequestContext
}

// RequestContext is passed to RequestPolicy.OnRequestBody.
// The complete buffered request body is available.
type RequestContext struct {
	*SharedContext

	// Current request headers (read-only for policies)
	// Policies use Get(), Has(), Iterate() methods for read-only access
	// Kernel updates via UnsafeInternalValues()
	Headers   *Headers
	Body      *Body
	Path      string
	Method    string
	Authority string
	Scheme    string
	Vhost     string

	// Deprecated: UpstreamInfo exposes the internal Envoy cluster name and its
	// resolved-upstream shape was incorrect. Use Upstream (*UpstreamRequestContext)
	// instead, which exposes Name rather than the internal cluster name.
	// Retained for backward compatibility; will be removed in a future release.
	UpstreamInfo *policyenginev1.UpstreamInfo

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target for this
	// request.
	Upstream *UpstreamRequestContext
}

// ─── Response-phase contexts ─────────────────────────────────────────────────

// ResponseHeaderContext is passed to ResponseHeaderPolicy.OnResponseHeaders.
// The response body is not yet available at this phase.
type ResponseHeaderContext struct {
	*SharedContext

	// Original request data (read-only, from request phase)
	RequestHeaders *Headers
	RequestBody    *Body
	RequestPath    string
	RequestMethod  string

	// Current response headers (read-only for policies)
	ResponseHeaders *Headers

	// Current response status code
	ResponseStatus int

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target and carries the
	// snapshot of the upstream response headers, captured before any policy
	// mutation.
	Upstream *UpstreamResponseContext
}

// ResponseContext is passed to ResponsePolicy.OnResponseBody.
// The complete buffered response body is available.
type ResponseContext struct {
	*SharedContext

	// Original request data (read-only, from request phase)
	RequestHeaders *Headers
	RequestBody    *Body
	RequestPath    string
	RequestMethod  string

	// Current response headers (read-only for policies)
	// Policies use Get(), Has(), Iterate() methods for read-only access
	// Kernel updates via UnsafeInternalValues()
	ResponseHeaders *Headers

	// Current response body (mutable)
	// nil if no body or body not required
	ResponseBody *Body

	// Current response status code
	ResponseStatus int

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target and carries the
	// snapshot of the upstream response headers, captured before any policy
	// mutation.
	Upstream *UpstreamResponseContext
}

// ─── Streaming contexts ──────────────────────────────────────────────────────

// StreamBody holds a single chunk of body data delivered during streaming processing.
// Unlike Body, it does not carry the "Present" flag — a chunk is always present by definition.
type StreamBody struct {
	// Chunk is the raw bytes for this piece of body data.
	// May be empty when EndOfStream is true (a terminal signal with no payload).
	Chunk []byte

	// EndOfStream signals that no more chunks will follow for this message.
	// Policies should finalize any accumulated state when true.
	EndOfStream bool

	// Index is the zero-based sequential position of this chunk within the stream.
	// The kernel increments this for every chunk delivered to the policy chain.
	// Useful for accumulation logic (e.g. "have I seen enough chunks yet?"),
	// first-chunk initialization, and debug logging.
	Index uint64
}

// RequestStreamContext is the per-chunk context passed to StreamingRequestBodyPolicy.
// It is structurally identical to RequestHeaderContext today, but kept as a distinct
// type so that streaming-specific fields (e.g. accumulated byte count, chunk index)
// can be added in the future without changing the header-phase contract.
// Headers are read-only; body data arrives via the StreamBody argument, not this struct.
type RequestStreamContext struct {
	*SharedContext

	// Current request headers (read-only)
	Headers   *Headers
	Path      string
	Method    string
	Authority string
	Scheme    string
	Vhost     string

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target for this
	// request.
	Upstream *UpstreamRequestContext
}

// ResponseStreamContext is the per-chunk context passed to StreamingResponseBodyPolicy.
// It mirrors ResponseHeaderContext — response body is delivered chunk-by-chunk
// via the StreamBody argument.
type ResponseStreamContext struct {
	*SharedContext

	// Original request data (read-only, from request phase)
	RequestHeaders *Headers
	RequestBody    *Body
	RequestPath    string
	RequestMethod  string

	// Current response headers (read-only)
	ResponseHeaders *Headers

	// Current response status code
	ResponseStatus int

	// Downstream holds the snapshot of the client request headers, captured
	// before any policy mutation.
	Downstream *DownstreamContext

	// Upstream identifies the route's resolved upstream target and carries the
	// snapshot of the upstream response headers, captured before any policy
	// mutation.
	Upstream *UpstreamResponseContext
}
